# serverless.yml
service: starwars-api
frameworkVersion: '3'
plugins:
  - serverless-dynamodb-local
  - serverless-offline
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["species", "Arn" ] }
functions:
  getSpecie:
    handler: src/index.handler
    events:
      - http: 'GET /species/{proxy+}'
  createSpecie:
    handler: src/index.handler
    events:
      - http: 'POST /species'
  getFilm:
    handler: src/index.handler
    events:
      - http: 'GET /films/{proxy+}'
  getFilms:
    handler: src/index.handler
    events:
      - http: 'GET /films'
resources:
  Resources:
    species:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: species
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH